apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: administration-service
  name: administration-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: administration-service
  strategy: { }
  template:
    metadata:
      labels:
        app: administration-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://212.237.231.147:3306/xui
            - name: SPRING_DATASOURCE_USERNAME
              value: "yahya"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "yahya"
          image: alismak/wolf-ott-administration-service:latest
          name: administration-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9010
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: administration-service-svc
  name: administration-service-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9010
  selector:
    app: administration-service
