apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: auth-service
    name: auth-service
    annotations:
        argocd.argoproj.io/sync-wave: "3"
spec:
    replicas: 3
    selector:
        matchLabels:
            app: auth-service
    strategy: { }
    template:
        metadata:
            labels:
                app: auth-service
        spec:
            imagePullSecrets:
                -   name: dockerhub-secret
            containers:
                -   env:
                        -   name: SPRING_PROFILES_ACTIVE
                            value: docker
                        -   name: SPRING_DATASOURCE_URL
                            value: jdbc:mysql://mysql:3306/xui
                        -   name: SPRING_DATASOURCE_USERNAME
                            value: "yahya"
                        -   name: SPRING_DATASOURCE_PASSWORD
                            value: "yahya"
                    image: alismak/auth-service:latest
                    name: auth-service-app
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 9001
                    resources: { }
            restartPolicy: Always
status: { }
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: auth-service-svc
    name: auth-service-svc
spec:
    type: ClusterIP
    ports:
        -   port: 80
            targetPort: 9001
    selector:
        app: auth-service
status:
    loadBalancer: { }
