apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-server
  name: config-server
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  strategy: {}
  template:
    metadata:
      labels:
        app: config-server
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: alismak/wolf-ott-config-server:latest
          name: config-server
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
  name: config-server
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: config-server
