apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: device-service
  name: device-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: device-service
  strategy: { }
  template:
    metadata:
      labels:
        app: device-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: device-service
          image: alismak/wolf-ott-device-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: wolf-ott-configmap
                  key: connection_string
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: wolf-ott-configmap
                  key: connection_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: wolf-ott-configmap
                  key: connection_password 
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: device-service-svc
  name: device-service-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9002
  selector:
    app: device-service
