apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-service
  namespace: wolf-ott
spec:
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      nodePort: 31500
  type: NodePort
  selector:
    app: eureka-discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery-deployment
  namespace: wolf-ott
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-discovery
  template:
    metadata:
      labels:
        app: eureka-discovery
    spec:
      containers:
        - name: eureka-discovery
          image: alismak/wolf-ott-discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-discovery-service"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
