apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-server-cm
data:
  discovery-server_address: "http://discovery-server-0.discovery-server.wolf-ott.svc.cluster.local:8761/eureka"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery-server
  name: discovery-server
spec:
  clusterIP: None
  ports:
    - name: discovery-server
      port: 8761
  selector:
    app: discovery-server

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-server
spec:
  serviceName: "discovery-server"
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: discovery-server
          image: alismak/wolf-ott-discovery-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-cm
                  key: discovery-server_address
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: discovery-server-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery-server
  name: discovery-server-lb
spec:
  selector:
    app: discovery-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761
      nodePort: 31500
