apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-service
  namespace: wolf-ott
spec:
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      nodePort: 31500
  type: NodePort
  selector:
    app: eureka-discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery-deployment
  namespace: wolf-ott
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-discovery
  template:
    metadata:
      labels:
        app: eureka-discovery
    spec:
      containers:
        - name: eureka-discovery
          image: springcloud/eureka:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-discovery-service"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eureka-discovery-ingress
  namespace: wolf-ott
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: eureka.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eureka-discovery-service
                port:
                  number: 8761
