apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-app
  name: frontend-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  strategy: { }
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - image: alismak/wolf-ott-frontend:latest
          name: frontend-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-svc
  name: frontend-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32200
  selector:
    app: frontend-app
