apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-service
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy: { }
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - env:
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: ' TRACE'
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka.wolf-ott.svc.cluster.local:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-svc.wolf-ott.svc.cluster.local:3306/xui
            - name: SPRING_DATASOURCE_USERNAME
              value: "yahya"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "yahya"
          image: alismak/wolf-ott-gateway-service:latest
          name: gateway-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service-svc
  name: gateway-service-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8181
      nodePort: 30100
      protocol: TCP
  selector:
    app: gateway-service
