apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: line-service
    name: line-service
    annotations:
        argocd.argoproj.io/sync-wave: "3"
spec:
    replicas: 3
    selector:
        matchLabels:
            app: line-service
    strategy: { }
    template:
        metadata:
            labels:
                app: line-service
        spec:
            imagePullSecrets:
                -   name: dockerhub-secret
            containers:
                -   env:
                        -   name: SPRING_PROFILES_ACTIVE
                            value: docker
                        -   name: SPRING_DATASOURCE_URL
                            value: jdbc:mysql://mysql:3306/xui
                        -   name: SPRING_DATASOURCE_USERNAME
                            value: "yahya"
                        -   name: SPRING_DATASOURCE_PASSWORD
                            value: "yahya"
                    image: alismak/line-service:latest
                    name: line-service
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 9004
                    resources: { }
            restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: line-service-svc
    name: line-service-svc
spec:
    type: ClusterIP
    ports:
        -   port: 80
            targetPort: 9004
    selector:
        app: line-service
