apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
  name: notification-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: alismak/notification-service:latest
          name: notification-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9005
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service-svc
  name: notification-service-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9005
  selector:
    app: notification-service
status:
  loadBalancer: {}
