apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server-service
  name: server-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-service
  strategy: { }
  template:
    metadata:
      labels:
        app: server-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-svc.wolf-ott.svc.cluster.local:3306/xui
            - name: SPRING_DATASOURCE_USERNAME
              value: "yahya"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "yahya"
          image: alismak/wolf-ott-server-service:latest
          name: server-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9006
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-service-svc
  name: server-service-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9006
  selector:
    app: server-service
