apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  strategy: { }
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_address
          image: alismak/wolf-ott-user-service:latest
          name: user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9009
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service-svc
  name: user-service-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9009
  selector:
    app: user-service
